//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robin.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robin.Locales.Ressources", typeof(Ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No WAV files found on device.
        /// </summary>
        internal static string BalloonTrayNoWavfilesFound {
            get {
                return ResourceManager.GetString("BalloonTrayNoWavfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device plugged in.
        /// </summary>
        internal static string BalloonTrayTextDevicePluggedIn {
            get {
                return ResourceManager.GetString("BalloonTrayTextDevicePluggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Removed.
        /// </summary>
        internal static string BalloonTrayTextDeviceRemoved {
            get {
                return ResourceManager.GetString("BalloonTrayTextDeviceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin is now Running.
        /// </summary>
        internal static string BalloonTrayTextRobinIsRunning {
            get {
                return ResourceManager.GetString("BalloonTrayTextRobinIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        internal static string BalloonTrayTextUploadComplete {
            get {
                return ResourceManager.GetString("BalloonTrayTextUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete with error.
        /// </summary>
        internal static string BalloonTrayTextUploadCompleteWithError {
            get {
                return ResourceManager.GetString("BalloonTrayTextUploadCompleteWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin.
        /// </summary>
        internal static string BalloonTrayTipTitleRobin {
            get {
                return ResourceManager.GetString("BalloonTrayTipTitleRobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Reporter : .
        /// </summary>
        internal static string BalloonTrayTipTitleStatusReporter {
            get {
                return ResourceManager.GetString("BalloonTrayTipTitleStatusReporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer complete and device cleaned.
        /// </summary>
        internal static string BalloonTrayTransferComplete {
            get {
                return ResourceManager.GetString("BalloonTrayTransferComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device plugged in.
        /// </summary>
        internal static string CurrentStatusDevicePlugIn {
            get {
                return ResourceManager.GetString("CurrentStatusDevicePlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device removed waiting for other device.
        /// </summary>
        internal static string CurrentStatusDeviceRemoved {
            get {
                return ResourceManager.GetString("CurrentStatusDeviceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumping files from device.
        /// </summary>
        internal static string CurrentStatusDumpingFile {
            get {
                return ResourceManager.GetString("CurrentStatusDumpingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle, waiting for a valid device to start working.
        /// </summary>
        internal static string CurrentStatusIdle {
            get {
                return ResourceManager.GetString("CurrentStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import document to DB.
        /// </summary>
        internal static string CurrentStatusImportDocToDb {
            get {
                return ResourceManager.GetString("CurrentStatusImportDocToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload audio file to DB.
        /// </summary>
        internal static string CurrentStatusUploadAudioToDb {
            get {
                return ResourceManager.GetString("CurrentStatusUploadAudioToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app.
        /// </summary>
        internal static string MenuCloseApp {
            get {
                return ResourceManager.GetString("MenuCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current status.
        /// </summary>
        internal static string MenuGetCurrentStatus {
            get {
                return ResourceManager.GetString("MenuGetCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login : .
        /// </summary>
        internal static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string MenuLogOut {
            get {
                return ResourceManager.GetString("MenuLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with windows.
        /// </summary>
        internal static string MenuStartWithWindows {
            get {
                return ResourceManager.GetString("MenuStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin.
        /// </summary>
        internal static string WinKeyRunWithWindows {
            get {
                return ResourceManager.GetString("WinKeyRunWithWindows", resourceCulture);
            }
        }
    }
}
